agentoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index,task,subtask,tools,generate_code,knowledgerep,post_symbol_sentiment,api_upload_document,api_trigger_agent
app_name  = 'agentoapp'

urlpatterns = [    
    path('', name='index',view=index),
    path('task/<str:action>/<int:id>', name='task',view=task),
    path('task/<int:taskId>/step/<int:step>/<str:action>', name='subtask',view=subtask),
    path('task/<int:taskId>/subtask/<int:step>/<str:action>', name='subtask',view=subtask),
    path('tools/<str:action>/<int:id>', name='tools',view=tools),
    path('genai', name='generate_code',view=generate_code),
    path('knowledgerep/<str:action>/<int:id>', name='knowledgerep',view=knowledgerep),
    path('api_upload_document/upload', name='api_upload_document',view=api_upload_document),
    path('api_trigger_agent', name='api_trigger_agent',view=api_trigger_agent),

    path('post_symbol_sentiment', name='post_symbol_sentiment',view=post_symbol_sentiment),

   


]

agentollama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('agentoapp.urls')),
    path('admin/', admin.site.urls),
]

agentoapp/models.py
from django.db import models
from django.dispatch import receiver
import os

class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

  

    def __str__(self):
        return self.name



class KnowledgeRep(models.Model):
    name = models.CharField(max_length=24,unique=True)
    description = models.CharField(max_length=128)
    associated_task = models.ForeignKey(Task,on_delete=models.DO_NOTHING,null=True,blank=True)
    
    def __str__(self):
        return str(self.name)


def user_directory_path(instance,filename):
   # file will be uploaded to MEDIA_ROOT
   return 'krep/{0}/{1}'.format(instance,filename) 

class KnowledgeRepFiles(models.Model):
    Knowledge_rep = models.ForeignKey(KnowledgeRep,on_delete=models.CASCADE)
    file = models.FileField(upload_to =user_directory_path)

    def __str__(self):
        return self.Knowledge_rep.name

@receiver(models.signals.post_delete, sender=KnowledgeRepFiles)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

SUBTASK_CHOICES = (
    ('AGENT', "Agent"),
    ('TOOL', "Tool"),
    ('CODE', "Code"),
)
 
class SubTask(models.Model):
    belongs_to = models.ForeignKey(Task,on_delete=models.DO_NOTHING)
    type = models.CharField(max_length=20,choices=(("TOOL",'Tool'),('RAG','RAG'),('LOOP','Loop')))
    model = models.CharField(max_length=24)
    name = models.CharField(max_length=100)
    context = models.CharField(max_length=2048)
    instruction = models.CharField(max_length=2048)
    outputFormatInstruction = models.CharField(max_length=2048)
    knowledgerep = models.ForeignKey(KnowledgeRep,on_delete=models.SET_NULL,null=True,blank=True)

    step = models.IntegerField()
   

    def __str__(self):
        return self.name
    
class Tool(models.Model):    
    name = models.CharField(max_length=100)
    context = models.CharField(max_length=2048)
    instruction = models.CharField(max_length=2048)
    outputFormatInstruction = models.CharField(max_length=2048)
    codeblock = models.TextField(null=True)
    def __str__(self):
        return self.name

class SubTaskTool(models.Model):
    subtask = models.ForeignKey(SubTask,on_delete=models.CASCADE)
    tool = models.ForeignKey(Tool,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.subtask} -  {self.tool}"

class TaskRun(models.Model):
    task = models.ForeignKey(Task,on_delete=models.DO_NOTHING)
    current_step = models.IntegerField(default=-1)
    current_step_status = models.CharField(max_length=24,choices=(("RUNNING",'Running'),('COMPLETED','Completed'),('FAILED','Failed')))

    
class TaskLog(models.Model):
    task_run = models.ForeignKey(TaskRun,on_delete=models.CASCADE)    
    log = models.TextField()

agentoapp/views.py
from django.shortcuts import render,redirect,HttpResponse,HttpResponseRedirect
from .models import SubTaskTool, Task,SubTask,Tool, TaskRun, TaskLog,KnowledgeRep,KnowledgeRepFiles
# Create your views here.
from .og import prompt,prompt_rag
from ollama import chat
from django.http import StreamingHttpResponse,JsonResponse
import json
from django.forms.models import model_to_dict

from ollama import ListResponse, list


from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
from pathlib import Path
import ollama
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.ollama import Ollama
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core import StorageContext

import chromadb
from llama_index.vector_stores.chroma import ChromaVectorStore
import json_repair
import re


def index(request):
    tasks = Task.objects.all().values()
    return render(request,'agentoapp/index.html',context={'tasks':tasks})

def task(request,action,id):
    print(action,id)
    print(request.POST)

    if action == 'viewlogs':
        # take top running job
        task_run = TaskRun.objects.filter(task=id).order_by('-id').first()
        task_logs = TaskLog.objects.filter(task_run=task_run)
        print(task_run)
        context = {
            'current_task_run_id': task_run.id,
            'current_step': task_run.current_step,
            'status': task_run.current_step_status,
            'task_run':task_run,
            'task_logs': task_logs
        }
        return render(request,'agentoapp/viewlogs.html',context=context)
 
    if action == 'status':       
        # take top running job
        task_run = TaskRun.objects.filter(task=id).order_by('-id').first()
        logs = TaskLog.objects.filter(task_run=task_run).order_by('id')
        
        # Prepare subtask-specific results
        subtask_results = {}
        for log in logs:
            # We try to extract metadata from the log if present
            # Format: <p>[STEP:X] [AGENT:Y] [TYPE:Z]</p>...
            if '[STEP:' in log.log:
                agent_match = re.search(r'\[AGENT:(.+?)\]', log.log)
                if agent_match:
                    agent_name = agent_match.group(1)
                    subtask_results[agent_name] = log.log

        return JsonResponse({
            'current_task_run_id': task_run.id,
            'current_step': task_run.current_step,
            'status': task_run.current_step_status,
            'subtask_results': subtask_results
        })
    if action == 'create' and request.method == 'POST':
        taskName = request.POST.get('taskName','')
        taskDescription = request.POST.get('taskDescription','')
        print(taskName,taskDescription)
        Task.objects.create(name=taskName,description=taskDescription)
    
    task = None
    steps = None
    st_list = []
    subtasks = None
    if id:
        task = Task.objects.get(id=id)
    # get steps asc
        # subtasks = SubTask.objects.filter(belongs_to=id).order_by('step').values()
        for st in SubTask.objects.filter(belongs_to=id).order_by('step'):
            print(st)  
            current_step = st.step
            found = False
            for stl in st_list:
                if stl['step'] == current_step:
                    found = True
                    stl['subtasks'].append(st)
            if not found:
                st_list.append({'step':st.step, 'subtasks':[st]})
                found = False
        subtasks = SubTask.objects.filter(belongs_to=id).order_by('step')
        print(subtasks)
            
    if action == 'run':
        print("RUN")
        model = request.GET.get('model', 'gemma3n:e4b')
        answer = execute_task_run(id=id,model=model)
        return HttpResponse(answer)
    response: ListResponse = list()
    available_models = [model.model for model in response.models]
    print(available_models)
    return render(request,'agentoapp/task.html',context={'action':action,'id':id,'task':task,'st_list':st_list,'available_models':available_models,'subtasks':subtasks})

def subtask(request,taskId,step,action):
    print(action,taskId,'step',step)
   
    if action == 'create':
        subTaskName = request.POST.get('subTaskName','')
        context = request.POST.get('context','')
        instruction = request.POST.get('instruction','')
        outputFormatInstruction = request.POST.get('outputFormatInstruction','')
        type = request.POST.get('type','')
        model = request.POST.get('model','gemma3n:e4b')
        
        
        id = int(request.POST.get('knowledgerep',0))
        knowledgerep = None
        if id:            
            knowledgerep = KnowledgeRep.objects.get(id=id)

            
        print(taskId,step,action)
        print(subTaskName,context,instruction,outputFormatInstruction)
        task = Task.objects.get(id=taskId)

        
        subTask = SubTask.objects.create(belongs_to=task,name=subTaskName,context=context,instruction=instruction,outputFormatInstruction=outputFormatInstruction,step=step,type=type,knowledgerep=knowledgerep,model=model)
        return redirect(f'/task/edit/{taskId}')
        # Task.objects.create(name=taskName,description=taskDescription)
    subtask = None
    if action == 'edit':
        # SUBTASK ID HAS BEEN PAASED AS STEP ID !!!
        subtask = SubTask.objects.get(id=step)
    if action == 'edit' and request.method == 'POST':
        print(request.POST)
        subTaskName = request.POST.get('subTaskName','')
        context = request.POST.get('context','')
        instruction = request.POST.get('instruction','')
        outputFormatInstruction = request.POST.get('outputFormatInstruction','')
        selectedTools =  request.POST.get('selectedTools','')
        knowledgerep = request.POST.get('knowledgerep','')
        model = request.POST.get('model','gemma3n:e4b')
        # print(type(selectedTools),selectedTools,selectedTools=='')
        if selectedTools != '':
            selectedTools = [int(t) for t in selectedTools.split(',')]
            if len(selectedTools) > 0:
                SubTaskTool.objects.filter(subtask=subtask).delete()
                for t in selectedTools:            
                    tool = Tool.objects.get(id=t)
                    SubTaskTool.objects.create(subtask=subtask,tool=tool)
        elif selectedTools == '':
            SubTaskTool.objects.filter(subtask=subtask).delete()
          
        subtask.name = subTaskName
        subtask.context = context
        subtask.instruction = instruction
        subtask.outputFormatInstruction = outputFormatInstruction
        subtask.model = model
        if knowledgerep:
            subtask.knowledgerep = KnowledgeRep.objects.get(id=knowledgerep) 
        subtask.save()
        print("POST")

    tools = Tool.objects.all()
    knowledgereps = KnowledgeRep.objects.all()
    assigned_tools = None
    if subtask:
        assigned_tools = SubTaskTool.objects.filter(subtask=subtask)
        
    page = None
    if subtask:
        page = f"{subtask.type.lower()}subtask"
    else:
        page = action

    response: ListResponse = list()
    available_models = [model.model for model in response.models]
    return render(request,f'agentoapp/{page}.html',context={'action':action,'taskId':taskId,'step':step,'subtask':subtask,'tools':tools,'assigned_tools':assigned_tools,'knowledgereps':knowledgereps,'available_models':available_models})
    

def tools(request,action,id):
    print(action,id)
    print(request.POST)
    back_url = request.META.get('HTTP_REFERER')
    if action == 'create' and request.method == 'POST':        
        toolName = request.POST.get('toolName','')              
        context = request.POST.get('context','')
        instruction = request.POST.get('instruction','')
        outputFormatInstruction = request.POST.get('outputFormatInstruction','')  
        codeblock = request.POST.get('codeblock','')  
        back_url = request.POST.get('back_url','')  

        print(toolName,context,instruction,outputFormatInstruction,codeblock)
        Tool.objects.create(name=toolName,context=context,instruction=instruction,outputFormatInstruction=outputFormatInstruction,codeblock=codeblock)
        return redirect(back_url)
    elif action == 'edit' and request.method == 'POST':
        tool = Tool.objects.get(id=id)
        toolName = request.POST.get('toolName','')              
        context = request.POST.get('context','')
        instruction = request.POST.get('instruction','')
        outputFormatInstruction = request.POST.get('outputFormatInstruction','')  
        codeblock = request.POST.get('codeblock','')  
        back_url = request.POST.get('back_url','')  

        print(toolName,context,instruction,outputFormatInstruction,codeblock)
        tool.name = toolName
        tool.context = context
        tool.instruction = instruction
        tool.outputFormatInstruction = outputFormatInstruction
        tool.codeblock = codeblock
        tool.save()
        return redirect(back_url)

    tool = None
    if action == 'edit' and request.method == 'GET':       
        tool = Tool.objects.get(id=id)
    

    existing_tools = Tool.objects.all()

    response: ListResponse = list()
    available_models = [model.model for model in response.models]

    return render(request,'agentoapp/tool.html',context={'action':action,'id':id,'back_url':back_url,'existing_tools':existing_tools,'tool':tool,'available_models':available_models})

def stream_llm(prompt,model):
    # https://dev.to/epam_india_python/harnessing-the-power-of-django-streaminghttpresponse-for-efficient-web-streaming-56jh
    print("stream_llm(prompt,model):")
    print(prompt)
    print(model)
    stream = chat(
        model=model,
        messages=[{'role': 'user', 'content': prompt}],
        stream=True,
    )

    for chunk in stream:        

agentoapp/templates/agentoapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@5.0.0-beta.2/daisyui.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>

<body class="container mx-auto p-4">

    <div class="flex justify-between items-center mb-8 border-b border-base-300 pb-4">
        <h1 class="text-3xl font-bold">Agents on Tasks </h1>
        <a class="btn btn-success text-white">Create a new task</a>
    </div>

    <div class="">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 items-start">
            <div class="">
                <div class="card bg-base-100 shadow-xl border border-base-200">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <h6 class="text-sm text-base-content/70 mb-2">Card subtitle</h6>
                        <p class="">Some quick example text to build on the card title and make up the bulk of
                            the
                            card's content.</p>
                        <div class="card-actions">
                            <a href="#" class="link link-primary no-underline hover:underline">Card link</a>
                            <a href="#" class="link link-primary no-underline hover:underline">Another link</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card bg-base-100 shadow-xl border border-base-200">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <h6 class="text-sm text-base-content/70 mb-2">Card subtitle</h6>
                        <p class="">Some quick example text to build on the card title and make up the bulk of
                            the
                            card's content.</p>
                        <div class="card-actions">
                            <a href="#" class="link link-primary no-underline hover:underline">Card link</a>
                            <a href="#" class="link link-primary no-underline hover:underline">Another link</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card bg-base-100 shadow-xl border border-base-200">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <h6 class="text-sm text-base-content/70 mb-2">Card subtitle</h6>
                        <p class="">Some quick example text to build on the card title and make up the bulk of
                            the
                            card's content.</p>
                        <div class="card-actions">
                            <a href="#" class="link link-primary no-underline hover:underline">Card link</a>
                            <a href="#" class="link link-primary no-underline hover:underline">Another link</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="card bg-base-100 shadow-xl border border-base-200">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <h6 class="text-sm text-base-content/70 mb-2">Card subtitle</h6>
                        <p class="">Some quick example text to build on the card title and make up the bulk of
                            the
                            card's content.</p>
                        <div class="card-actions">
                            <a href="#" class="link link-primary no-underline hover:underline">Card link</a>
                            <a href="#" class="link link-primary no-underline hover:underline">Another link</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>

</body>

</html>

agentoapp/templates/agentoapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | Agents on Tasks</title>
    <!-- Stable CDN Links -->
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap');

        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            background-color: #f3f4f6;
            background-image: radial-gradient(circle at top right, rgba(99, 102, 241, 0.05), transparent 40%),
                              radial-gradient(circle at bottom left, rgba(168, 85, 247, 0.05), transparent 40%);
        }

        .premium-card {
            background: white;
            border-radius: 1.5rem;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.08);
            border: 1px solid rgba(0, 0, 0, 0.05);
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .premium-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 35px 60px -15px rgba(0, 0, 0, 0.12);
            border-color: rgba(99, 102, 241, 0.2);
        }

        .hero-title {
            background: linear-gradient(135deg, #1e293b 0%, #334155 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .icon-box {
            @apply flex items-center justify-center w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600;
        }
    </style>
</head>

<body class="min-h-screen py-12 px-4 selection:bg-indigo-100 flex flex-col items-center pt-20">
    <!-- Branding Clip -->
    <a href="{% url 'agentoapp:index' %}" class="fixed top-0 left-1/2 -translate-x-1/2 z-[100] group">
        <div class="bg-white px-8 py-3 rounded-b-3xl shadow-[0_10px_30px_-5px_rgba(0,0,0,0.1)] border-x border-b border-gray-100 flex items-center gap-3 animate-in slide-in-from-top duration-700 group-hover:bg-gray-50 transition-colors">
            <i class="bi bi-robot text-indigo-600 text-xl"></i>
            <span class="font-black tracking-[0.2em] text-gray-800 text-xs uppercase">Agentollama</span>
        </div>
    </a>
    <div class="w-full max-w-6xl">
        <!-- Header -->
        <header class="flex flex-col md:flex-row justify-between items-start md:items-center mb-16 gap-8 px-2">
            <div>
                <div class="flex items-center gap-4 mb-2">
                    <div class="p-3 bg-indigo-600 rounded-2xl text-white shadow-lg shadow-indigo-200">
                        <i class="bi bi-rocket-takeoff-fill text-2xl"></i>
                    </div>
                    <h1 class="text-4xl font-extrabold tracking-tight hero-title uppercase">Agent Control Center</h1>
                </div>
                <p class="text-gray-500 font-medium pl-1">Deploy, manage, and monitor your autonomous agent network</p>
            </div>
            
            <div class="flex flex-wrap gap-4">
                <a class="btn btn-primary h-14 px-8 rounded-xl bg-indigo-600 border-none shadow-xl shadow-indigo-100 font-black text-white" href="{% url 'agentoapp:task' action='create' id=0 %}">
                    <i class="bi bi-plus-circle-fill"></i> New Workspace
                </a>
                <a class="btn btn-neutral h-14 px-8 rounded-xl border-none shadow-lg font-black" href="{% url 'agentoapp:knowledgerep' action='create' id=0 %}">
                    <i class="bi bi-database-fill-add"></i> Intel Repository
                </a>
                <a class="btn btn-ghost h-14 px-6 border border-gray-200 hover:bg-white rounded-xl font-bold text-gray-400" href="/tools/create/0">
                    <i class="bi bi-tools"></i> Architect Tools
                </a>
            </div>
        </header>

        <!-- Main Content (Workspace Grid) -->
        <main class="w-full">
            <div class="flex items-center gap-4 mb-8">
                <h2 class="text-xs font-black text-indigo-500 uppercase tracking-[0.3em]">Active Workspaces</h2>
                <div class="h-px bg-gray-200 flex-grow"></div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {% for task in tasks %}
                <div class="premium-card flex flex-col overflow-hidden">
                    <div class="h-1.5 bg-gradient-to-r from-indigo-500 to-purple-500"></div>
                    <div class="p-8 flex-grow">
                        <div class="flex items-start gap-4 mb-6">
                            <div class="w-12 h-12 shrink-0 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-600 shadow-inner">
                                <i class="bi bi-cpu-fill text-xl"></i>
                            </div>
                            <div class="space-y-1">
                                <div class="flex items-center gap-2">
                                    <i class="bi bi-robot text-gray-300"></i>
                                    <h3 class="text-xl font-black text-gray-800 tracking-tight leading-tight">{{task.name}}</h3>
                                </div>
                                <span class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Workspace #{{task.id}}</span>
                            </div>
                        </div>

                        <div class="space-y-4 mb-8">
                            <div class="flex gap-3 items-start">
                                <i class="bi bi-chat-left-quote text-indigo-400 mt-1"></i>
                                <p class="text-gray-500 text-sm font-medium leading-relaxed">{{task.description|truncatewords:25}}</p>
                            </div>
                        </div>
                    </div>

                    <div class="p-4 bg-gray-50 border-t border-gray-100 flex justify-end">
                        <a href="{% url 'agentoapp:task' action='edit' id=task.id %}" class="btn btn-ghost btn-block h-12 rounded-xl group hover:bg-indigo-600 hover:text-white transition-all font-black text-gray-500">
                            ENTER COMMAND CENTER <i class="bi bi-arrow-right-short text-xl group-hover:translate-x-1 transition-transform"></i>
                        </a>
                    </div>
                </div>
                {% empty %}
                <div class="col-span-full py-24 text-center">
                    <div class="w-24 h-24 bg-white rounded-3xl flex items-center justify-center text-gray-200 mx-auto mb-6 shadow-sm border border-gray-100">
                        <i class="bi bi-layers-half text-5xl"></i>
                    </div>
                    <h3 class="text-xl font-black text-gray-400 uppercase tracking-widest">No Active Workspaces</h3>
                    <p class="text-gray-400 text-sm font-medium mt-2">Begin by orchestrating your first task pipeline.</p>
                </div>
                {% endfor %}
            </div>
        </main>

        <!-- Footer -->
        <footer class="mt-32 pb-12 text-center">
            <div class="h-px bg-gray-200 w-12 mx-auto mb-8"></div>
            <p class="text-[10px] font-black text-gray-300 uppercase tracking-[0.6em]">Agents on Tasks &copy; 2025 Architecture</p>
        </footer>
    </div>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
</body>

</html>

agentoapp/templates/agentoapp/index_backup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agents on Tasks Dashboard</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom CSS -->
    <!-- <link href="https://bootswatch.com/5/simplex/bootstrap.css" rel="stylesheet"> -->
    <style>
        .header {
            padding: 2rem 0;
            margin-bottom: 2rem;
            background-color: var(--bs-light);
            border-bottom: 1px solid var(--bs-border-color);
        }

        .task-card {
            height: 100%;
            transition: transform 0.2s;
        }

        .task-card:hover {
            transform: translateY(-5px);
        }
    </style>
</head>

<body>
    <!-- Header -->
    <header class="header">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="display-5 mb-0">Agents on Tasks</h1>
                <a class="btn btn-success" href="{% url 'agentoapp:task' action='create' id=0%}">
                    <i class="bi bi-plus-circle me-2"></i>Create New Task
                </a>
                <a class="btn btn-success" href="{% url 'agentoapp:knowledgerep' action='create' id=0 %}">
                    <i class="bi bi-plus-circle me-2"></i>Create knowledge Base
                </a>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container py-4">
        <div class="row g-4">
            {% for task in tasks %}
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card task-card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title text-primary">{{task.name}}</h5>
                        <p class="card-text text-secondary mb-3">{{task.description}}</p>
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'agentoapp:task' action='edit' id=task.id %}"
                                class="btn btn-outline-primary btn-sm">
                                Open Task
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
            <span class="text-muted">© 2025 Agents on Tasks. All rights reserved.</span>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
</body>

</html>